### ISSUE TITLE
Feed of Songs

### ISSUE THREAD

**Issue by themikail** [themikail/capstone-project#1]
**Value proposition**
- As a user
- I want to view a list of shared songs
- in order to connect with my friends

**Description**
<img width="273" alt="Bildschirmfoto 2023-05-17 um 12 10 54" src="https://github.com/themikail/capstone-project/assets/66737755/a6711992-66a3-4394-a54c-6d127b030e90">

**Acceptance criteria**
- [ ] List scrolls vertically
- [ ] Shared listening music
- [ ] clicking twice on the post to like and show a heart

**Tasks**
- [ ] Create branch
- [ ] generate dummy JSON data
- [ ] Generate dummy-data (MP3 Music)
- [ ] If it's the first user story: Global styles
